name             'test_berks'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test_berks'
long_description 'Installs/Configures test_berks'
version          '0.1.0'
